# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NakamaTestSwfit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NakamaTestSwfit
  pod 'Nakama', :git => 'https://github.com/Allan-Nava/nakama-swift.git', :branch => 'master'	

  target 'NakamaTestSwfitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NakamaTestSwfitUITests' do
    # Pods for testing
  end

end
